### ISSUE TITLE
file.info(collapse_file) error

### ISSUE THREAD

**Issue by Deanho** [kroganlab/mist#18]
Hi,
I am trying to run the MIST algorithm on my affinity proteomics data. I think I have everything in the right format etc. Upon running the first phase - preprocessing with data.txt and keys.txt files only - I get the following error in terminal (Mac, which permission set correctly):
>> LOADING DEPENDENCIES...
>> All required R libraries accounted for.
>> PREPROCESSING FILES
	READING FILES
	FILTERING COMMON CONTAMINANTS
	  FILTERED 193 CONTAMINANTS
	MERGING KEYS WITH DATA
	  20 TOTAL BAITS DETECTED
	  20/20 BAITS DETECTED IN DATA FILE
	  20/20 BAITS DETECTED IN KEYS FILE
	CONVERTING TO MATRIX
Error in file.info(collapse_file) : invalid filename argument
Calls: main ... preprocess.main -> preprocess.createMatrix -> file.info
Execution halted

I can't work out what's wrong. From google searches of similar error messages, I think it may be something to do with the class of the filename, but I'm unsure which line (in which script) I need to modify.
Any ideas?
Regards,
Dean

**Comment by jvondollen** [comment]
Hi Dean,

You say that you're using only the keys and data files for this, so I'm assuming there are no collapse, specificity exclusions, and remove files. There may be something with the error handling of a blank file going on. Could you try creating a blank/empty Collapse file and reference it in the config file? You may have to do the same for the specificity exclusions and remove files.

Best,
John

**Comment by Deanho** [comment]
Hi John,

Thanks for the prompt reply. Yes. That did the trick, partly. What I had to do was have non-blank 'collapse', 'specificity_exclusions' and 'remove' files. Only then would the pipeline (pre-MIST) run to completion. If I simply specify blank (empty) files in the yaml config file, it still failed....?
What happens if I don't want to exclude any samples (i.e. exclusions file required to be blank)?
Dean

**Comment by jvondollen** [comment]
Hi Dean,

What I meant by a blank file is to create just an empty (txt) file somewhere, and reference that in the config file (collapse : Path_to_your_blank_file, etc.). Or have I misunderstood your question?

~john

**Comment by jvondollen** [comment]
I've pushed a couple new updates to take care of this issue. Let us know if this is still an issue.
